apiVersion: apps/v1
kind: Deployment
metadata:
  name: koth
  labels:
    app: koth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koth
  template:
    metadata:
      labels:
        app: koth
    spec:
      containers:
        - name: koth
          image: docker.io/kickinthedoor/koth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
