apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: koth-frontend-ingress
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /koth/api
            pathType: Prefix
            backend:
              service:
                name: koth
                port:
                  number: 8000
          - path: /koth/
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /koth
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
